# =============================================================================
# Chimera Operating System — Limine Configuration (v8.x Format)
# limine.conf
# =============================================================================

timeout: 0

/Chimera Operating System
    protocol: limine
    kernel_path: boot():/kernel.elf
    module_path: boot():/bin/cat
    module_path: boot():/bin/chmod
    module_path: boot():/bin/clear
    module_path: boot():/bin/cp
    module_path: boot():/bin/dash
    module_path: boot():/bin/date
    module_path: boot():/bin/df
    module_path: boot():/bin/echo
    module_path: boot():/bin/false
    module_path: boot():/bin/kill
    module_path: boot():/bin/ls
    module_path: boot():/bin/mkdir
    module_path: boot():/bin/mv
    module_path: boot():/bin/pwd
    module_path: boot():/bin/rm
    module_path: boot():/bin/sh
    module_path: boot():/bin/sleep
    module_path: boot():/bin/true
    module_path: boot():/private/etc/hosts
    module_path: boot():/private/etc/motd
    module_path: boot():/private/etc/version
    module_path: boot():/sbin/ifconfig
    module_path: boot():/sbin/ping
    module_path: boot():/usr/bin/basename
    module_path: boot():/usr/bin/calc
    module_path: boot():/usr/bin/curl
    module_path: boot():/usr/bin/dirname
    module_path: boot():/usr/bin/env
    module_path: boot():/usr/bin/grep
    module_path: boot():/usr/bin/guiapp
    module_path: boot():/usr/bin/head
    module_path: boot():/usr/bin/hexdump
    module_path: boot():/usr/bin/kilo
    module_path: boot():/usr/bin/machdemo
    module_path: boot():/usr/bin/memload
    module_path: boot():/usr/bin/nc
    module_path: boot():/usr/bin/neofetch
    module_path: boot():/usr/bin/proclist
    module_path: boot():/usr/bin/seq
    module_path: boot():/usr/bin/smpdemo
    module_path: boot():/usr/bin/stat
    module_path: boot():/usr/bin/tail
    module_path: boot():/usr/bin/tcc
    module_path: boot():/usr/bin/tee
    module_path: boot():/usr/bin/touch
    module_path: boot():/usr/bin/uname
    module_path: boot():/usr/bin/uptime
    module_path: boot():/usr/bin/wc
    module_path: boot():/usr/bin/whoami
    module_path: boot():/usr/bin/yes
    module_path: boot():/usr/sbin/wserver
    module_path: boot():/System/Library/CoreServices/WindowServer
