
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:7 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/Users/fvr/.gemini/antigravity-ide/bin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/Users/fvr/.bun/bin/"
      - "/Users/fvr/.local/bin/"
      - "/Users/fvr/.antigravity-ide/antigravity-ide/bin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/pkg/env/global/bin/"
      - "/Library/Apple/usr/bin/"
      - "/Applications/Wireshark.app/Contents/MacOS/"
      - "/Users/fvr/.spicetify/"
      - "/Users/fvr/.lmstudio/bin/"
    searched_directories:
      - "/Users/fvr/.gemini/antigravity-ide/bin/uname"
      - "/opt/homebrew/bin/uname"
      - "/opt/homebrew/sbin/uname"
      - "/Users/fvr/.bun/bin/uname"
      - "/Users/fvr/.local/bin/uname"
      - "/Users/fvr/.antigravity-ide/antigravity-ide/bin/uname"
      - "/usr/local/bin/uname"
      - "/System/Cryptexes/App/usr/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/Users/fvr/.gemini/antigravity-ide/bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/Users/fvr/.bun/bin"
        - "/Users/fvr/.local/bin"
        - "/Users/fvr/.antigravity-ide/antigravity-ide/bin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/pkg/env/global/bin"
        - "/Library/Apple/usr/bin"
        - "/Applications/Wireshark.app/Contents/MacOS"
        - "/Users/fvr/.spicetify"
        - "/Users/fvr/.lmstudio/bin"
...
